server.port: 8082

addressClient:
  baseUrl: http://localhost:8081

customerClient:
  baseUrl: http://localhost:8081

spring:
  output:
    ansi:
      enabled: always
  application:
    name: api-service

management:
  server:
    port: 8080
  endpoint:
    beans:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    actuator:
      enabled: true
    web:
      base-path: /actuator
      exposure:
        include: health
      enabled-by-default: false
  security:
    enabled: false

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces